export const API = "https://localhost:3001/"
export const LOGIN = "https://localhost:3001/oauth/login"
export const LOCAL_API = "https://localhost:3001/"
export const CANVAS_URL = "https://montclair-preprod.instructure.com/"
export const EXTERNAL_TOOL_ID = "111"